### ISSUE TITLE
Multiple ActionMenus in a view result in flickering when clicked through

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/spectrum-web-components#819] opened 2020-08-11 02:51 UTC
### Expected Behaviour

I would expect:
+ If AutoMenu 1 is open, and AutoMenu 2 is clicked, then AutoMenu 1 will close and AutoMenu 2 opens.
+ If AutoMenu 1 is open, and AutoMenu 2 is clicked, then AutoMenu 1 stays open and Auto Menu 2 also opens.

This could be attribute on sp-action-menus, for example:

+ `closeWhenOtherActionMenuIsOpened` = true | false
+ `closeAllOtherActionMenusWhenOpened` = true | false

Or something like that

### Actual Behaviour

When AutoMenu 1 is open, and AutoMenu 2 is clicked, then AutoMenu 1 stays open (until IT is clicked again to close) and AutoMenu 2 flickers open and immediately closes.

### Reproduce Scenario (including but not limited to)

1. Navigate to: https://webcomponents.dev/edit/SXG2Xy46DSQerjVKTYZK
1. Click on the first instance of the Action Menu and open it
1. Then click on the 2nd instance, and watch it flicker open/shut

#### Steps to Reproduce

Place 2 or more Action Menus on a page, open one of them, and then try opening the other(s) before closing the initially opened one.

#### Platform and Version

+ Chrome latest
+ "@spectrum-web-components/action-menu": "^0.5.4",

#### Sample Code that illustrates the problem

https://webcomponents.dev/edit/SXG2Xy46DSQerjVKTYZK

**Comment by Westbrook** [comment] 2020-08-11 12:33
@davidjgonzalez thanks for this issue. The specific open/close bug that you've outlined here is a duplicate of #809 and to make it easier to track I'd like to close this issue in favor of it. There's a work around of not using webpack (Rollup isn't exhibiting this issue in build), but if that's not possible a fix for the timing across build/test/etc environments is in active development.

Your separate feature request around `closeWhenOtherActionMenuIsOpened` is interesting, and I'd appreciate some more information about your use case and the functionality you'd expect in that case in a new issue, if you didn't mind. Particularly, I see there being some issues with accessibility that we'd need to organize an approach to before it would be possible to add something like that to the library and an issue dedicated to that functionality would be the best place to work that out before any development was started. Thanks in advance for you support in this way!

**Closed by Westbrook** 2020-08-11 12:33 UTC

**Comment by davidjgonzalez** [comment] 2020-08-11 14:23
@Westbrook gotcha! Sorry - I reviewed Action Menu tagged issues before posting rather than Dropdown. Makes sense since AM uses DD under the covers.

Wrt to the Feature Request, I suppose a bit depends on what the default behavior is/supposed to be for multiple dropdowns in a view. 

My expectation as a user, is if I have a dropdown open, and I click on ANOTHER control, I am indicating that I am "done" w that control and thus is can collapse to its unopened state. 

If the expected behavior is to have open dropdowns close when another dropdown is engaged, then this feature becomes moot.

 If the default behavior is to just leave all dropdowns open until they are explicitly closed (which IMO is not idiomatic of dropdowns) then it would be nice to have a way to tell the dropdowns to close when a different dropdown is engaged.

**Comment by Westbrook** [comment] 2020-08-11 14:53
The default is that only one dropdown should be open at a time, and if you open a second one, the first one should close, that's the issue in #809 that we will be correcting. I may have misunderstood:

> If AutoMenu 1 is open, and AutoMenu 2 is clicked, then AutoMenu 1 stays open and Auto Menu 2 also opens.

If that's actually a feature you want, we'd need to add it after the bug is corrected, and I'd like to track the expanded requirements (particularly around keyboard accessibility) in a new issue so that we can work out the intended feature in a way that supports all types of users interacting with the element before committing to add the functionality.
