### ISSUE TITLE
[Bug]: self-managed sp-tooltip is not getting closed on mouse right click 

### ISSUE THREAD

**Issue by ananpal** [adobe/spectrum-web-components#2942] opened 2023-02-21 10:19 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

* tooltip view should be closed on right click.

### Actual behavior

* tooltip view stays on right click, even moving the mouse from view the tooltip view stays.

### Screenshots

![Screenshot 2023-02-21 at 3 44 08 PM](https://user-images.githubusercontent.com/29448061/220316241-f13567e5-86ab-47f7-82bc-91a799f200ef.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Create a spectrum button(or any view) and add self managed tooltip to it.
2. Hover on the button view
3. Right Click

**Comment by hunterloftis** [comment] 2023-02-21 16:41
@ananpal I've tried to reproduce the issue [here](https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/VmbuRedDUMmN4amLK7ie/src/index.ts?branch=tooltip-focus%40hdGxURl7S4S8pgMAQioer2pp5E12&p=stories) (navigate to story-1).

This test shows the behavior I would expect, however:

https://user-images.githubusercontent.com/364501/220404486-8dff12c7-e809-4bdc-bede-3d75bb6d2562.mov

I've added configuration variables at the top to try to break the behavior. Tooltips respond to focus, and native context menus receive focus. If a custom context menu does not manage focus in an accessible way, the tooltip will not go away because, as far as it's aware, the triggering element is still focused and the menu is purely a visual change.

You can see this behavior with native tooltips by opening a context menu, then seeing that you can immediately navigate its items via keyboard:

https://user-images.githubusercontent.com/364501/220405359-bcca71fd-74c9-4f45-b5ea-87f729b93678.mov

The demo with sp-tooltip matches this behavior:

https://user-images.githubusercontent.com/364501/220405890-850994ab-1c77-4986-8de9-5c2c13633aca.mov

Can you please confirm whether or not your usage above sends focus to the context menu, and is subsequently navigable by keyboard? That will help narrow down the issue.

**Comment by Westbrook** [comment] 2023-12-11 15:38
Closing as works as expected.

**Closed by Westbrook** 2023-12-11 15:38 UTC
Labels: enhancement
