### ISSUE TITLE
Can someone please tell me what this means and is...

### ISSUE THREAD

**Issue by wright79mit** [adobe/spectrum-web-components#541] opened 2020-03-15 03:13 UTC
### Reproduce Scenario (including but not limited to)

01-24 06:34:53.382	tUHM:SetupWizardWelcomeActivity.UHM onCreate() Intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.samsung.android.app.watchmanager cmp=com.samsung.android.app.watchmanager/.setupwizard.SetupWizardWelcomeActivity (has extras) }
01-24 06:34:53.382	tUHM:SetupWizardWelcomeActivity.UHM onCreate() Bundle: null
01-24 06:34:53.382	tUHM:SetupWizardWelcomeActivity.density [2.625], densityDpi [420], heightPixels [2064], widthPixels [1080]
01-24 06:34:53.387	tUHM:TWatchManagerApplication.getAppContext()
01-24 06:34:53.387	tUHM:TWatchManagerApplication.mAppContext = com.samsung.android.app.twatchmanager.TWatchManagerApplication@9dc5ede
01-24 06:34:53.388	tUHM:InstallationUtils.hasInstallPermission() return:true
01-24 06:34:53.388	tUHM:HostManagerUtils.isSamsungDeviceWithCustomBinary, res [false]
01-24 06:34:53.388	tUHM:TWatchManagerApplication.getAppContext()
01-24 06:34:53.388	tUHM:TWatchManagerApplication.mAppContext = com.samsung.android.app.twatchmanager.TWatchManagerApplication@9dc5ede
01-24 06:34:53.388	tUHM:HostManagerUtils.isMaximumPowerSavingMode, res [false]
01-24 06:34:53.389	tUHM:TWatchManagerApplication.getAppContext()
01-24 06:34:53.389	tUHM:TWatchManagerApplication.mAppContext = com.samsung.android.app.twatchmanager.TWatchManagerApplication@9dc5ede
01-24 06:34:53.389	tUHM:InstallationUtils.hasInstallPermission() return:true
01-24 06:34:53.389	tUHM:HostManagerUtils. isSamsungDevice() MANUFACTURER :samsung return :true
01-24 06:34:53.389	tUHM:SetupWizardWelcomeActivity.printDB starts
01-24 06:34:53.389	tUHM:SetupWizardWelcomeActivity.getAllDeviceRegistryData()
01-24 06:34:53.389	tUHM:RegistryDbManagerWithProvider.queryAllDeviceRegistryData:
01-24 06:34:53.394	tUHM:RegistryDbManagerWithProvider.queryAllDeviceRegistryData, size = 1
01-24 06:34:53.394	tUHM:SetupWizardWelcomeActivity.Print all device data:
01-24 06:34:53.394	tUHM:SetupWizardWelcomeActivity.
DB::[-- DeviceRegistryData --]
DB::packagename : com.samsung.android.gearoplugin
DB::deviceBtID : ##:##:##:##:37:B6
DB::deviceFixedName : Gear S3 (17B6)
DB::isConnected : 1
DB::lastLaunch : 1
DB::neckletAutoConnection : null
DB::supportsPairing : 1

**Comment by bengfarrell** [comment] 2020-03-15 03:29
This doesn't appear relevant at all to this project. It appears to be a very verbose and non-erroneous Android device log. This repository and related issues are for Spectrum Web Components, mainly intended for browser usage. I might guess that you posted here by mistake

**Comment by Westbrook** [comment] 2020-03-15 13:58
Hi @wright79mit, thanks for the issue and your interest in Spectrum Web Components. At current, it is difficult to say that the issue you've experienced here is related to our project. If you have a specific reproduction case that in some way led you to this above stack trace, please add it to the issue and we'll see how best we can support this context. If not, we wish you the best of luck with your endeavors but will have to close this issue as there is no clear resolution target that we can support at this time.

**Comment by Westbrook** [comment] 2020-03-26 23:35
Closing for lack of participation.

**Closed by Westbrook** 2020-03-26 23:35 UTC
