### ISSUE TITLE
[Bug]: Editable Slider not rounding values 

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#4201] opened 2024-03-21 12:55 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

Editable Slider onChange `event.target.value` should print 0.56 after adding`0.55999999999` on the NumberField 

### Actual behavior

Slider is printing 0.55999999999 instead of 0.56

### Screenshots

<img width="1272" alt="Screenshot 2024-03-21 at 6 24 26 PM" src="https://github.com/adobe/spectrum-web-components/assets/8790510/e7e6bb0a-bcfb-496c-92f2-cf92f27d885a">

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

Following are steps :-

Change min="0.25" to min="0.10"
In textbox , type 0.55999999999
In change i can see 0.55999999999 is getting logged instead of 0.56
Note: this bug is reproducible for few number like 0.55999999999  and NOT for [0.5999999999](tel:05999999999). And it is reproducible only for min value less than 0.11. 

JIRA bug: https://jira.corp.adobe.com/browse/CCEX-102612

**Comment by Westbrook** [comment] 2024-03-22 14:32
Would this be considered a duplicate of #3817?

**Closed** 2024-04-30 12:07 UTC
Labels: bug, Component: Slider, triage
