### ISSUE TITLE
[Feat]: sp-textfield  custom icon like valid

### ISSUE THREAD

**Issue by whyds000** [adobe/spectrum-web-components#4139] opened 2024-03-06 07:51 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield 

### Description of the requested feature

sp-textfield  custom icon like valid or invalid

**Comment by Westbrook** [comment] 2024-03-15 22:51
Could you please share a more complete example of what you think should be possible with `sp-textfield` in this context? Example code, designs, or demonstrations would be a big help in understanding what you're looking for with this request.

**Comment by Westbrook** [comment] 2024-03-22 01:56
Without a more complete reproduction, we'll be closing this issue on the 25th of March.

**Comment by Westbrook** [comment] 2024-03-25 16:55
We're closing this due to a lack of information to move forward. If you have more information in the future feel free to reopen this or a new issue with your updated. Thanks!

**Closed by Westbrook** 2024-03-25 16:55 UTC
Labels: enhancement, triage
