### ISSUE TITLE
[Bug]:  tooltip placement is incorrect if parent is having 'transform' attr or if it has 'contain' attribute 

### ISSUE THREAD

**Issue by cdprashanth** [adobe/spectrum-web-components#3718] opened 2023-10-12 11:02 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tootlip

### Expected behavior

tooltip should work irrespective of parent' 'transform' or 'contain' attributes 

### Actual behavior

 tooltip placement is incorrect if parent is having 'transform' attr or if it has 'contain' attribute 
it works fine if we remove 'transform' and 'contain' attribute from the element (sp-field-label. here)

### How can we reproduce this issue?

https://studio.webcomponents.dev/edit/626bqpGg4XNLho8ZIHsY/src/index.ts?p=stories

### Sample code that illustrates the problem

// tooltip placement is incorrect if parent is having 'transform' attr or if it has 'contain' attribute 
import {
  LitElement,
  html,
  customElement,
  TemplateResult,
} from "lit-element";
import "@spectrum-web-components/switch/sp-switch.js";
import "@spectrum-web-components/grid/sp-grid.js";
import "@spectrum-web-components/field-label/sp-field-label.js";

import "@spectrum-web-components/tooltip/sp-tooltip.js";
import "@spectrum-web-components/icon/sp-icon.js";

@customElement("my-switch")
export default class MySwitch extends LitElement {
  protected render(): TemplateResult {
    return html`

  <sp-grid id="AI2450" tabindex="0" 
  style="
outline: none !important; display: block; position: relative; 
contain: size layout; min-width: 100%; min-height: 400px;" tabindex="0"
> 

 <sp-field-label class="add_document_swatch_view" dir="ltr" 
style="transform: translate(1px, 1px); display: flex; align-items:
 center; justify-content: center; position: absolute;
  left: 0px; top: 0px; width: 24px; height: 24px;" id="sp-field-label-23" size="m"><sp-icon id="AI2328" dir="ltr" aria-hidden="true" size="m"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18px" height="18px" viewBox="0 0 18 18" style="enable-background:new 0 0 18 18;" xml:space="preserve" fill="currentColor">
<style type="text/css">
	.st0{fill:#6E6E6E;}
</style>
<g id="surface1">
	<path d="M14.3,8.2H9.8V3.7c0-0.2-0.2-0.4-0.4-0.4H8.6c-0.2,0-0.4,0.2-0.4,0.4v4.5H3.7c-0.2,0-0.4,0.2-0.4,0.4v0.8
		c0,0.2,0.2,0.4,0.4,0.4h4.5v4.5c0,0.2,0.2,0.4,0.4,0.4h0.8c0.2,0,0.4-0.2,0.4-0.4V9.8h4.5c0.2,0,0.4-0.2,0.4-0.4V8.6
		C14.8,8.4,14.6,8.2,14.3,8.2"></path>
</g>
</svg></sp-icon>
<sp-tooltip self-managed="" offset="0" id="AI2329" dir="ltr" placement="bottom">Add swatch</sp-tooltip>
</sp-field-label>

<base-view class="swatch_view swatch_1" id="AI3187" tabindex="-1" 
style="touch-action: manipulation; user-select: none; -webkit-user-drag: none; 
-webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: absolute; width: 24px; height: 24px;
 left: 24px; top: 0px; overflow: hidden; box-sizing: border-box; transform: translate(28px, 2px);">
 <stack-view id="AI3188" style="position: absolute; left: 0px; top: 0px; width: 24px; height: 24px; 
 overflow: hidden;">

 <sp-field-label dir="ltr" style="display: flex; align-items: center; 
 justify-content: center; position: absolute; left: 0px; top: 0px; width: 24px; height: 24px;" 
 id="sp-field-label-82" size="m">
 <sp-icon id="AI3064" dir="ltr" aria-hidden="true" size="m">
 </sp-icon><img class="unscaled-img" id="AI3065" 
 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAADZJREFUSEtjvHv37n8GGgLGUQsIhe5oEBEKIYbRIBoNIoIhQFDBaCoaDSKCIUBQwWgqGgFBBABVdVYp7MsTqgAAAABJRU5ErkJggg==" 
 width="24" height="24" 
 style="user-select: none; position: absolute; left: 0px; top: 0px; 
 width: 24px; height: 24px;">
 <base-view id="AI3189" style="position: absolute; left: 0px;
  top: 0px; width: 24px; height: 24px; overflow: hidden;"><canvas id="AI3062" width="48"
   height="48" style="position: absolute; left: 0px; top: 0px; width: 24px; height: 24px;">
   </canvas></base-view>
   <sp-tooltip self-managed="" offset="0" id="AI3066" dir="ltr" placement="bottom">New swatch 5</sp-tooltip>
   </sp-field-label>

</stack-view></base-view>

</sp-grid>

 `;
  }
}

### Logs taken while reproducing problem

https://studio.webcomponents.dev/edit/626bqpGg4XNLho8ZIHsY/src/index.ts?p=stories

**Comment by Westbrook** [comment] 2023-10-26 13:19
From my point of view, the issue here is neither the `transform` or `contain` values. In [this demo](https://studio.webcomponents.dev/edit/KsYbERgDWcwlt8vZKfsE/src/index.ts?p=stories), I've removed `overflow: hidden` from the `id="AI3187"` element and it appear to work as expected.

At large, the broad use of `overlay: hidden` in your code likely points to broader issues that you should be addressing directly rather than hiding with a CSS property that increases the overall cost of rendering your application and can have unintended side effects, like disrupting this delivery.

We'll see if we can't hunt down where in the Floating UI library this situation arises, but it's possible that is take some time to wash out of the various dependency levels.

**Comment by timsnadden** [comment] 2023-12-08 02:07
Here is a [reproduction](https://codepen.io/karbonhq/pen/dyaaLKR) that shows how wrapping a `<sp-action-menu>` in an element with `container-type: inline-size` prevents it from positioning the menu correctly in relation to the trigger.

**Comment by Westbrook** [comment] 2024-01-03 00:17
Closing as can't reproduce. We addressed `container-type` in #3908

**Closed by Westbrook** 2024-01-03 00:17 UTC
Labels: Discovery
