### ISSUE TITLE
[Bug]: Tooltip is clickable when used with sp-action-button

### ISSUE THREAD

**Issue by PrashantYadav207** [adobe/spectrum-web-components#4082] opened 2024-02-21 09:03 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-button, sp-tooltip

### Expected behavior

when sp-tooltip is used with sp-action then sp-tooltip should not be clickable and even though the tooltip is clickable it should not invokes the click events of sp-action-button.

### Actual behavior

when sp-tooltip is used with sp-action then sp-tooltip becomes clickable and invokes the click events of sp-action-button.

### Screenshots

https://github.com/adobe/spectrum-web-components/assets/160720989/ae813cb7-37eb-4352-9d71-9dc5d49dd968

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/0NhX8q5en0guLfQcz2dw/src/index.ts?p=stories

**Comment by Westbrook** [comment] 2024-02-22 01:57
Duplicate of #3969

**Closed by Westbrook** 2024-02-22 01:57 UTC
Labels: bug, triage
