### ISSUE TITLE
[Bug]: Able to scroll in the underlay

### ISSUE THREAD

**Issue by audknu** [adobe/spectrum-web-components#4189] opened 2024-03-15 18:28 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

underlay

### Expected behavior

Users should not be able to scroll in the underlay. All SWC storybook examples and documentation examples should reflect this expected behavior.

I confirmed this expected behavior with Spectrum design. This aligns with the React Spectrum v3 implementation.

See [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/Dialog.html) for an example. For the fix, I suggest looking at their implementation in their code base:

https://github.com/adobe/spectrum-web-components/assets/24359834/2a62809e-7617-405b-8cf5-2bda89ec82b1

### Actual behavior

A user can scroll in the underlay

https://github.com/adobe/spectrum-web-components/assets/24359834/6730ed90-e4d5-42ce-a977-2938ade60f01

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/underlay/
2. Click on an example to view the underlay 
3. Scroll
4. Observe how the page in the underlay reacts to scrolling

**Comment by Westbrook** [comment] 2024-03-15 21:34
Dupe of #3849

**Closed by Westbrook** 2024-03-15 21:34 UTC
Labels: bug, triage
