### ISSUE TITLE
Differences Spectrum Web Components and Coral Spectrum

### ISSUE THREAD

**Issue by elrumo** [adobe/spectrum-web-components#934] opened 2020-10-07 14:57 UTC
### Expected Behaviour
It's not an issue, but I wasn't sure where to ask.  What is the difference between the Spectrum Web Components and [Coral Spectrum](https://opensource.adobe.com/coral-spectrum/documentation/)? Maybe some clarification with the differences could be added to the documentation, or even a list of all the Spectrum flavours there are available, i.e. React Spectrum, Coral Spectrum, Spectrum CSS....

**Comment by Westbrook** [comment] 2020-10-07 17:22
Duplicate of #933.

**Closed by Westbrook** 2020-10-07 17:22 UTC

**Comment by elrumo** [comment] 2020-10-07 17:37
Thanks for closing it, not sure why it was duplicated.
