### ISSUE TITLE
[Bug]: when sp-picker is open on mobile, screen is scrollable

### ISSUE THREAD

**Issue by cdvu1** [adobe/spectrum-web-components#2536] opened 2022-08-23 21:24 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

When sp-picker is open in mobile, scrolling should be blocked or the menu should be dismissed. 

### Actual behavior

When the sp-picker menu is open on mobile, and I am able to scroll around while the menu is still open.

### Screenshots

Video attached in this Google Drive link:
https://drive.google.com/file/d/1ItsjsvXjiWJTtwYcrnI5Fhg0YSODwdgp/view?usp=sharing

### How can we reproduce this issue?

1. Go to [Lightroom Academy article](https://lightroom.adobe.com/academy/travel/packing-travel-gear#focal-length-interactive)
2. Make sure you are on a mobile device
3. Use your finger to scroll up and down around where the menu area is and you will see the screen is scrollable while sp-picker is still displayed.

**Comment by Westbrook** [comment] 2024-01-06 00:27
Want to make sure there was visibility into this approach to this situation: https://github.com/adobe/spectrum-web-components/issues/3849#issuecomment-1841552963

**Comment by Westbrook** [comment] 2024-03-15 21:39
Dupe of #3849

**Closed by Westbrook** 2024-03-15 21:39 UTC
Labels: bug, Component: Overlay, Component: Picker, Mobile, Post overlay API
