### ISSUE TITLE
[Feat]: Customising the space between an Action button (3 dots) and popover menu

### ISSUE THREAD

**Issue by vikalpgupta** [adobe/spectrum-web-components#3135] opened 2023-04-20 07:04 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu/sp-popover

### Description of the requested feature

Hi All, I have a requirement of customising the space between an Action button and popover (marked in red below) in case of an Action menu. I can see there is a variable --spectrum-overlay-animation-distance(--spectrum-picker-m-texticon-popover-offset-y) which can be configured to achieve the desired custom result but I am not able to find a way to customise the same, given the sp-popover’s active overlay is appended directly to body and because of it customisation via variable override is not inherited from Action menu’s implementation, also I don’t see any suitable slot API available for overriding popover html, can anyone help out here? Thanks

### Mockups or screenshots

![image](https://user-images.githubusercontent.com/2239918/233283649-95642783-1c94-427a-acf1-9e8cdf3ad3d4.png)

### Implementation notes or ideas

Support via context-menu slot, for eg using the below to create the customised popover
```
<sp-popover slot="context-menu">
    // Custom styling here to configure component or pass custom variables values
    <sp-menu>${this.renderContextMenuItems(this.contextMenuItems)}</sp-menu>
</sp-popover>
```

**Comment by Westbrook** [comment] 2023-04-22 06:03
Sounds good. Closing as works as intended.

**Closed by Westbrook** 2023-04-22 06:03 UTC
Labels: enhancement, triage
