### ISSUE TITLE
[Bug]: Touch/down state not working in sp-slider

### ISSUE THREAD

**Issue by react-dev92** [adobe/spectrum-web-components#2836] opened 2023-01-09 09:48 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

When clicking on sp-slider, the appearance of slider dot should change as per touch/down state. This is working fine in react-spectrum but not working in spectrum-web-component

### Actual behavior

When clicking on sp-slider, the appearance of slider dot does not get updated

### Screenshots

https://user-images.githubusercontent.com/88501261/211280523-ed386991-aec2-4aec-ba25-b5de39a3bbb0.mov

https://user-images.githubusercontent.com/88501261/211280561-5db88359-a1b3-4686-b7fb-c0917bde8b6d.mov

### How can we reproduce this issue?

1. Go to 'https://opensource.adobe.com/spectrum-web-components/components/slider/'
2. Click on ' any slider and drag it'

5. See error that down state is not getting updated

For expected behaviour repeated above steps at 
https://react-spectrum.adobe.com/react-spectrum/Slider.html

https://user-images.githubusercontent.com/88501261/211280458-2cdd6b0a-9f4a-45c5-bef5-aee98cfbb50c.mov

**Comment by najikahalsema** [comment] 2023-01-10 20:15
Not a bug, so closing the issue.

**Closed by najikahalsema** 2023-01-10 20:15 UTC
Labels: bug, triage

**Comment by react-dev92** [comment] 2023-01-12 06:46
> Not a bug, so closing the issue.

@najikahalsema Could you explain why this is not considered a bug?

**Comment by bengfarrell** [comment] 2023-01-12 17:55
I think you're both right. Its probably not a SWC issue directly, as the same behavior appears in Spectrum CSS https://spectrum.adobe.com/page/slider.

As Spectrum Web Components rely on and match Spectrum CSS directly, the issue is not SWC.

That said, it IS an issue. I've created a bug on the Spectrum CSS side and referred back to XD component specs. Unfortunately, the down state is not called out in the documentation on the Spectrum CSS page, so it's probably an oversight
