### ISSUE TITLE
[Bug]: Can't open SplitButton more than once

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1909] opened 2021-11-05 19:56 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Split Button

### Expected behavior

You can open a Split Button more than once

### Actual behavior

Once you open/close a split button, it can't be opened again. Also seeing a console error after this happens:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'matches')
    at HTMLElement.focus (Picker.js:179)
    at HTMLElement.focus (SplitButton.js:101)
    at Object.manageFocusAfterCloseWhenLastOverlay (overlay-stack.js:441)
    at Object.hideAndCloseOverlay (overlay-stack.js:473)
Picker.js:179 

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/split-button/
2. Click on a split button to open it
3. Close/re-open the split button

**Comment by Westbrook** [comment] 2021-11-05 19:59
Duplicate of #1894

**Closed by Westbrook** 2021-11-05 19:59 UTC
Labels: bug, Component: Split Button, triage
