### ISSUE TITLE
[tests] Proposal to incorporate framework integration testing

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#1807] opened 2021-09-21 14:02 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

Would be nice to include automated testing that runs the suite against components that are rendered using React.  Could also include other frameworks as well but it seems like React would add the most value.

**Comment by najikahalsema** [comment] 2022-10-26 19:18
closing as duplicate of #2390

**Closed as completed by najikahalsema** 2022-10-26 19:18 UTC
Labels: Component:Tooling, Component:Testing
