### ISSUE TITLE
[Feat]: Allow overlays to decide if they can be closed

### ISSUE THREAD

**Issue by nickschaap** [adobe/spectrum-web-components#2959] opened 2023-02-23 15:32 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Description of the requested feature

There are many cases where an application might show a blocking overlay (e.g. lost connection popup, loading popup, paywall, login popup, persistent popovers). It would be helpful if the SWC Overlay system allowed self managed overlays to decide whether they can be closed externally (e.g. clicking on an underlay, clicking outside of a popover, pressing the ESC key). This would allow overlays to require users to select an explicit option and/or let the application to decide when to close the overlay.

This is similar to what is described as `popover=manual` behavior in the [Open UI popover explainer](https://open-ui.org/components/popover.research.explainer#popover-vs-dialog).

This should be a definite addition to the new Overlay API, but in the meantime it could be useful to provide this functionality with the current Overlay system as well.

### Implementation notes or ideas

  We could possibly add another `ManagedOverlayContent` lifecycle callback that returns a boolean if the overlay should be allowed to close.

https://github.com/adobe/spectrum-web-components/blob/643fcff10b6e455611fda76040ea0d29ecac5df9/packages/overlay/src/overlay-stack.ts#L35

**Comment by Westbrook** [comment] 2023-02-23 15:57
duplicate of #1853

Checkout `type: page` in https://github.com/adobe/spectrum-web-components/discussions/2764 where we hope to address this.

**Closed by Westbrook** 2023-02-23 15:57 UTC
Labels: enhancement, triage
