### ISSUE TITLE
[Bug]:  Setting the attribute 'icons' to none is not hiding the default icon. We have to create a dummy span and add it to icon slot. 

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2985] opened 2023-03-07 13:17 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Expected behavior

 Setting the attribute 'icons' to none is not hiding the default icon. We have to create a dummy span and add it to icon slot. 

### Actual behavior

Default icon is still visible.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/action-menu/
2. Inspect any action menu and set icon=none.

**Comment by bmandal2** [comment] 2023-03-08 05:12
Thanks. In that case we should probably clarify in the documentation of action menu.
<img width="1347" alt="Screenshot 2023-03-08 at 10 41 03 AM" src="https://user-images.githubusercontent.com/127212746/223625195-46604e89-99e8-41de-82ab-dd7ed6aab324.png">

**Comment by najikahalsema** [comment] 2023-03-09 19:18
To-do:
1. Remove `icons` from action-menu API table
2. Add a description for icons in picker API table

**Comment by Westbrook** [comment] 2023-07-19 13:50
Duplicate of #2557

**Closed by Westbrook** 2023-07-19 13:50 UTC
Labels: Component: Action Menu, Component: Picker, Documentation
