### ISSUE TITLE
[Bug]: Slider: css style issues after update to v0.32

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3358] opened 2023-06-23 10:01 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider, SliderHandle

### Expected behavior

1. ~Slider label should align with value (centered) in non-editable version~
<img width="213" alt="Screenshot 2023-06-23 at 11 52 22" src="https://github.com/adobe/spectrum-web-components/assets/29090947/462d2ffc-5e16-4398-97b7-53c2c7363841">

2. ~Slider variant=tick should not have any extra margin-block-end~
<img width="235" alt="Screenshot 2023-06-23 at 11 52 55" src="https://github.com/adobe/spectrum-web-components/assets/29090947/f0353b03-9a74-4253-8d86-a42ffb65f5e0">

3. Slider with multiple slider handles: slider handles should stay on-top of track (for example by using higher z-index to overlay track)
<img width="342" alt="Screenshot 2023-06-23 at 11 53 10" src="https://github.com/adobe/spectrum-web-components/assets/29090947/b9f2d972-6291-4d11-9538-336f117dec30">

### Actual behavior

After last update to v0.32 we experienced the following issues with slider component.
1. Slider label is not centered with value in non-editable version
<img width="214" alt="Screenshot 2023-06-23 at 11 59 09" src="https://github.com/adobe/spectrum-web-components/assets/29090947/4fb76972-df23-4aa6-abe3-1ef884b542f2">

2. Slider variant=tick have a large extra margin-block-end
<img width="233" alt="Screenshot 2023-06-23 at 11 59 27" src="https://github.com/adobe/spectrum-web-components/assets/29090947/f7ed3c9a-03ca-4e2a-ad25-f6018ca78e00">

3. Slider with multiple slider handles: (first) left most slider handle is overlaid by track as it has z-index: 1 instead of 2 at least.
<img width="395" alt="Screenshot 2023-06-23 at 11 59 43" src="https://github.com/adobe/spectrum-web-components/assets/29090947/b16b89a5-28cb-4ed1-b64d-f3fa06f94bcb">
<img width="32" alt="Screenshot 2023-06-23 at 11 59 51" src="https://github.com/adobe/spectrum-web-components/assets/29090947/93202b50-b553-4bb2-a32e-74a5b430cb8a">

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment] 2023-06-23 12:02
1. @pfulton I brought this up with the design team when we were working on bringing Core Tokens into this pattern. It comes from the "value" not being treated as a Field Label and receiving unique styles that are not 100% the same. If we're not making that an _actual_ Field Label (which has it's own issues on our end) in the CSS implementation, could we do something about sharing more closely the style rules thereof?
2. This also appears in the [CSS implementation](https://opensource.adobe.com/spectrum-css/slider.html#tick). It appears to originate from CSS not having a delineation between the Tick Slider and the Tick Slider with Tick Labels. When the Tick Slider _does not_ have Tick Labels, this margin does not seem to be required. Do you think that's something that could be added to the CSS implementation? If not, the rule is hung on a unique selector within the pattern, so we could leverage our CSS conversion process to place this rule on the right situation.
3. @spdev3000 I'm not able to get this to happen with _just_ two Slider handles, are you able to help with a repro of that case? e.g. [this](https://opensource.adobe.com/spectrum-web-components/components/slider-handle/#range-slider) and [this](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--two-handles) don't seem to exhibit this issue. With three Slider handles I do see it [in the docs site](https://opensource.adobe.com/spectrum-web-components/components/slider-handle/#multi-handle-slider-with-ordered-handles), but not [in Storybook](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--three-handles-pc), which is confusing. It appears to be a situation with the calculations on the SWC side, when it arises, but need to figure out _when_ it arises to be able to correct. Will dig deeper.
4. Also of note, while touching the Slider at large, there is a selector in CSS `.spectrum-Slider-labelContainer + .spectrum-Slider-controls` that does not currently translate to SWC due to an altercation we've made to the DOM structure. This processes to `#label-container + #controls` in SWC, but need to become `#label-container + #track #container` to apply correctly.

**Comment by Westbrook** [comment] 2023-09-11 20:24
@spdev3000 It looks like you no. 3 is the last part of this that we haven't actively addressed. This is because I'm not able to recreate this situation. Would you be able to provide a repro?

**Comment by Westbrook** [comment] 2023-12-11 15:44
@spdev3000 closing as can't repro. If you're still having issue specific to no. 3 in the OP, please open a new issue with expanded reproduction steps.

**Closed by Westbrook** 2023-12-11 15:44 UTC
Labels: bug, Component: Slider, Spectrum CSS, Needs repro
