### ISSUE TITLE
[Bug]: Slider change closes overlay when using inside of tray

### ISSUE THREAD

**Issue by raullucero** [adobe/spectrum-web-components#4214] opened 2024-03-25 16:52 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

OverlayTrigger, Tray and Slider

### Expected behavior

Overlay won't dissapear after changing the slider inside of the tray

### Actual behavior

I trigger an overlay with a slider as content and after updating for the first time the slider, the whole overlay closes. 

the weird thing is this only happen when you interact with the slider for the first time, if you interact with other content it won't close

### Screenshots

https://github.com/adobe/spectrum-web-components/assets/2336266/c3ae2fc5-0234-4ee1-87ab-9ad7432a460d

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Click in the overlay trigger button
2. Change slider value
3. See behavior

### Sample code that illustrates the problem

https://codesandbox.io/p/sandbox/vigilant-cherry-4z78zd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltrto4c300063b6mv1rlky59%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltrto4c300023b6mshtgdd9k%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltrto4c300033b6mgm7gtvn7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltrto4c300053b6mterlizsi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltrto4c300023b6mshtgdd9k%2522%253A%257B%2522id%2522%253A%2522cltrto4c300023b6mshtgdd9k%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltrto4c300053b6mterlizsi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrto4c300043b6mecp1yslt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltrto4c300053b6mterlizsi%2522%252C%2522activeTabId%2522%253A%2522cltrto4c300043b6mecp1yslt%2522%257D%252C%2522cltrto4c300033b6mgm7gtvn7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltrto4c300033b6mgm7gtvn7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Westbrook** [comment] 2024-05-09 21:51
Duplicate of #4406.

**Closed by Westbrook** 2024-05-09 21:51 UTC
Labels: bug, triage
