### ISSUE TITLE
[Bug]: sp-tabs indicator fails to update correctly after the tabs element dynamically update

### ISSUE THREAD

**Issue by monkeyjabs** [adobe/spectrum-web-components#3179] opened 2023-05-04 03:05 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Expected behavior

When dynamically updating the sp-tab items within the sp-tabs component, the indicator should still be working correctly.

### Actual behavior

After dynamically change the sp-tab elements, clicking each tab the indicator is not working correctly.

### Screenshots

![PixelSnap 2023-05-03 at 20 04 12](https://user-images.githubusercontent.com/4380525/236104179-b6416e12-e5c8-40ad-9dcd-45d31a5710c7.png)

### How can we reproduce this issue?

1. Go to this example: https://studio.webcomponents.dev/edit/JwMP9IzpS8ySVxjBlwdv/src/index.ts?p=stories
2. Click on "Group 2" button
3. Click on any item on the tabs
4. Observe

**Comment by blunteshwar** [comment] 2024-05-22 07:36
In the implementation `repeat` method is used and we have downward dependency in case of `sp-tags` and `sp-tag`.
When `map` method is used it works just fine.
https://studio.webcomponents.dev/edit/yj2S80cI5yLa1HJhhp9f/src/index.ts?branch=testing3%404f6qBpw9HIMVQgAKtr1OJexT9el1&p=stories

**Comment by blunteshwar** [comment] 2024-05-22 07:36
Closing this because the issue is in user's implementation

**Closed by blunteshwar** 2024-05-22 07:36 UTC
Labels: bug, Component: Tabs
