### ISSUE TITLE
[Feat]: Support for adding tooltips and theme changes on sp-icon

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#3306] opened 2023-06-12 12:29 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

spectrum-icon

### Description of the requested feature

Currently, spectrum icon doesn't have support to show tooltips or theme changes. we have some workarounds to fix this inside illustrator web (like wrapping sp-icon inside a tooltip to support these features)

### Mockups or screenshots
![selected areas appearing dark in dark mode](https://github.com/adobe/spectrum-web-components/assets/125646446/9fe385b1-2a67-4bee-87e8-f9f9ab346210)

**Comment by Westbrook** [comment] 2023-06-22 13:57
Can you please share a reproduction abstract from the Ai code base? At first glance, it appears you may be leveraging Icons in an inaccessible manner, which leads you to this output.

**Comment by Westbrook** [comment] 2023-06-22 13:59
Also, Icon are not intended to be interactive elements, which means that they cannot accept hover/focus events as are needed for Tooltips. You likely want to use a different pattern as the trigger of a Tooltip. See https://spectrum.adobe.com/page/contextual-help/ or similar.

**Comment by Westbrook** [comment] 2023-07-18 12:54
Icons not being interactive element, but merely a visual representation of such an element, whether you leverage something like Contextual Help (in the above comment) or you deliver you Icon and Tooltip in a larger interface, like a[ Field Label](https://studio.webcomponents.dev/edit/VmbuRedDUMmN4amLK7ie/src/index.ts?branch=label%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories), the fix here is proper usage, not change of feature set.

Closing.

**Closed by Westbrook** 2023-07-18 12:54 UTC
Labels: enhancement, triage
