### ISSUE TITLE
[Bug]: overlay system does not manage body scroll

### ISSUE THREAD

**Issue by adbehahn** [adobe/spectrum-web-components#4173] opened 2024-03-13 19:16 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Expected behavior

When showing e.g. a dialog as a full-screen takeover, body scroll should be disabled.

### Actual behavior

It is not disabled by the overlay system, and needs to be disabled manually by the client.

### How can we reproduce this issue?

Desktop browsers.

**Comment by Westbrook** [comment] 2024-03-15 21:34
Closing as a dupe of #4189

**Closed by Westbrook** 2024-03-15 21:34 UTC
Labels: bug, triage
