### ISSUE TITLE
[switch] native checkbox showing in latest Firefox

### ISSUE THREAD

**Issue by tirithen** [adobe/spectrum-web-components#1460] opened 2021-05-17 10:11 UTC
### Expected Behaviour

The sp-switch and sp-checkbox tags should render identically in Firefox as in Chromium based browsers

### Actual Behaviour

The native checkbox renders as well in latest Firefox.

### Reproduce Scenario (including but not limited to)

Visit https://opensource.adobe.com/spectrum-web-components/components/switch with a Firefox browser.

#### Steps to Reproduce

Visit https://opensource.adobe.com/spectrum-web-components/components/switch with a Firefox browser.

#### Platform and Version

I would expect any platform (I was using updated Arch Linux with Gnome when taking the screenshot).

Firefox version 88.0.1

#### Sample Code that illustrates the problem

![Skärmbild från 2021-05-17 12-07-13](https://user-images.githubusercontent.com/245811/118472257-ec7a6e00-b708-11eb-9dfa-7afff6d67d53.png)
![Skärmbild från 2021-05-17 13-21-05](https://user-images.githubusercontent.com/245811/118480618-c4900800-b712-11eb-8c58-3ebbbec856ba.png)

**Comment by Westbrook** [comment] 2021-05-17 11:59
Hi @tirithen I'm sorry that you're running into this situation, however I'm having trouble recreating the issue that you've run into here. In version 88.0.1, both for macOS and win10, I do not see this issue. What's more neither of those contexts render the `<checkbox>` element that would be what is peaking out in the results you've shared as a circle (generally a precarious shape for a checkbox). Could you supply some extended information about your usage? Browser versions, whether this occurs with various of your seemingly numerous browser plugins turned off, etc?

What's more, could you compare the following URLs for similar experience?

https://opensource.adobe.com/spectrum-web-components/components/checkbox The `sp-switch` element is based functionally off of the `sp-checkbox` element, and I'd like to make sure this isn't happening in that context as well.

https://opensource.adobe.com/spectrum-css/switch.html All of our elements are stylistically based on the Spectrum CSS project, and I'd like to make sure this isn't an issue we're being provided with upstream.

Thanks for you support in this endeavor while we look to sort out what you're experiencing here.

**Comment by tirithen** [comment] 2021-05-18 07:45
Thanks, and thanks for testing it out in Windows and MacOS.

The reason that the checkbox shows seem to be the opacity 0.0001 value that seem to be rounded off up to 1. When I set it to 0 or set `apperance: none` the checkbox is hidden and the component seem to be usable.

Example of fixes:

![native-checkbox](https://user-images.githubusercontent.com/245811/118611999-a8957080-b7bd-11eb-85dd-fd4a59bee412.gif)

System setup:

* Firefox version is 88.0.1
* Gnome 40.1.0 (on Arch Linux)

![Skärmbild från 2021-05-18 09-35-33](https://user-images.githubusercontent.com/245811/118612061-b4813280-b7bd-11eb-9bda-3ec8bb13d1fc.png)
![Skärmbild från 2021-05-18 09-36-13](https://user-images.githubusercontent.com/245811/118612077-b5b25f80-b7bd-11eb-9f24-5e795d17eccc.png)

**Comment by Westbrook** [comment] 2021-05-18 11:37
I see. Thanks for hunting down some origin story on this!

I'm not sure that the projects we work with to ensure the delivery of our elements would count themselves as supporting Arch Linux. Can you help me track the right people to discuss this with by checking https://opensource.adobe.com/spectrum-css/switch.html to see if this situation occurs there? Also, did you find that a similar situation occurs with https://opensource.adobe.com/spectrum-web-components/components/checkbox?

**Comment by tirithen** [comment] 2021-05-18 12:52
Yes, it seems that in both these places they lack `appearance: none;` (https://developer.mozilla.org/en-US/docs/Web/CSS/appearance) and rely only on `opacity: .0001` to hide the native checkbox which would not be enough to hide it.

![Skärmbild från 2021-05-18 14-46-50](https://user-images.githubusercontent.com/245811/118653577-fa52f080-b7e7-11eb-82ca-337c2105b11f.png)

![Skärmbild från 2021-05-18 14-47-12](https://user-images.githubusercontent.com/245811/118653583-faeb8700-b7e7-11eb-88f5-c43b61f3f78e.png)

`opacity: 0;` would also do the trick, that worked when I tried it, and you can for example see Google using it for their MWC components https://material-components.github.io/material-components-web-components/demos/checkbox/

![Skärmbild från 2021-05-18 14-51-25](https://user-images.githubusercontent.com/245811/118654190-97ae2480-b7e8-11eb-8bef-65ae805c6767.png)

**Comment by Westbrook** [comment] 2021-05-19 21:48
Thanks for hunting through this, I've created https://github.com/adobe/spectrum-css/issues/1195 to track. It looks like the team agrees with the change, so hopefully we'll be able to see this entry the library, soon!

**Comment by tirithen** [comment] 2021-05-21 09:01
Sounds great!

**Comment by Westbrook** [comment] 2021-06-11 10:37
For tracking: https://github.com/adobe/spectrum-css/pull/1208

**Comment by hunterloftis** [comment] 2021-08-23 21:09
To help narrow down OS/browser combinations, I'm unable to reproduce this in Firefox 90.0 on Ubuntu 20.10:

![image](https://user-images.githubusercontent.com/364501/130519722-c968d4f4-f443-48df-bdf9-0012546d8078.png)

**Comment by tirithen** [comment] 2021-08-24 13:50
@Westbrook thanks for following this up.

I tested the link you sent, https://checkbox-linux--spectrum-web-components.netlify.app/ both sp-checkbox and sp-switch now looks as intended.

However my computer is now running Firefox 91.0.1 and Chromium 92.0.4515.159 and I can no longer reproduce the problem even if I remove the `opacity: 0;` that you added so now it works with either `opacity: 0;` or `opacity: 0.0001;`. Maybe this was corrected in Firefox and/or Firefox + Gnome combination.

I hope this information is somewhat helpful for you anyhow.

Link as is `opacity: 0;`
![Skärmbild från 2021-08-24 15-47-09](https://user-images.githubusercontent.com/245811/130628315-fbb59faa-f6ce-45c1-90a0-99920f2cc57e.png)

With only `opacity: 0.0001;`
![Skärmbild från 2021-08-24 15-47-25](https://user-images.githubusercontent.com/245811/130628323-5d7d6077-57d3-4dce-bb74-6023a25a663a.png)

**Comment by Westbrook** [comment] 2021-08-24 13:53
@tirithen I love it when this _fix themselves_ 🙈. If that's the case, I'm going to close this issue for now. Please feel free to reopen it if you run into issues in the future. I'll also close our PR of this a wait for the upstream change to come down and "fix it for real".

Thanks again for reporting and your patience through the process 🙇🏼 !

**Closed by Westbrook** 2021-08-24 13:53 UTC
