### ISSUE TITLE
[Feat]: Separate placeholder text color from input text color

### ISSUE THREAD

**Issue by pwong09** [adobe/spectrum-web-components#4103] opened 2024-02-29 16:11 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

search, textfield

### Description of the requested feature

Currently, we have css variables like:
`--spectrum-search-color-default` and `--spectrum-search-color-key-focus`
`--spectrum-textfield-text-color-default` and `--spectrum-textfield-text-color-valid`
However these variables control the text color of the `<input>` element AND its placeholder.
  

It would be great if we could separate these colors since typically a placeholder color is defaulted to a lighter gray and it is not text that a user can modify. The placeholder color should not be the same as the input's text color.

### Mockups or screenshots

Example using Google's search bar
Placeholder:
![Screenshot 2024-02-29 at 8 09 13 AM](https://github.com/adobe/spectrum-web-components/assets/91284556/de15faea-6109-4437-8dcc-ab66a5f1c716)

After typing in a query:
![Screenshot 2024-02-29 at 8 09 19 AM](https://github.com/adobe/spectrum-web-components/assets/91284556/2a4ac877-e78c-432f-8f59-f65e4ce56bb3)

### Implementation notes or ideas

There is a `--spectrum-textfield-placeholder-font-size` variable, so a color variable for placeholder can be something like `--spectrum-textfield-placeholder-default-color` and we can replace the color property in `.input::placeholder`

**Comment by Westbrook** [comment] 2024-02-29 16:24
The design team in conjunction with the accessibility team has gone back and forth on the difficulties a user faces when presented with placeholder test. At this juncture I'm not sure that they'll be move to add functionality in this way. However, if you'd like motion on this, the best path is to ensure your design team is directly in contact with Spectrum to outline the use cases they are attempting to address.

**Comment by KayiuCarlson** [comment] 2024-03-11 17:43
Hi @pwong09 @Westbrook , I'm adding a comment here of what I've discussed with Pearl on 3/1/24 on Slack so maybe we could close this ticket if you all wish. 

In terms of the usage on the placeholder text, I want to add some extra context that our Content strategist (Jess Sattell) recently shared in another channel because I think she explained it well.

> _the text within a search field is [the label for the field](https://spectrum.corp.adobe.com/page/search-field/#Include-a-label) first, placeholder text/prompt text, second. So a search field is a bit different from other input fields because the label is also the placeholder text. For example, both of these strings:_
> 
> - _Search_
> - _Search for photos, videos, and more_
> 
> _Both are functioning as labels (technically, field labels). It just happens to look like placeholder text because it's within the field._
> 
> _The second example (longer one) reads more like placeholder text because of the message; it's giving some examples of the kinds of things you could search for. This is the messaging role that placeholder text (or [help text](https://spectrum.corp.adobe.com/page/help-text/)) would normally serve. But its functional identity is that it's a label._
> 
> _The key here is also that even if the label disappears when someone enters a search term, there's still no context lost from a string like "Search for photos, videos, and more" because that message is a suggestion (placeholder text) — not a requirement (help text) for an effective search result._

Also on the Spectrum design site, we have documented in the [Search component](https://spectrum.corp.adobe.com/page/search-field/#Label-and-icon) that "_A search field should include a **label** and a search icon. In the default state before a search term is input, the **label** is in regular body text style **to meet contrast ratios** and to show that **this is a field label, not placeholder text**._"

We've also documented that for the Text field, we actually [don't support "placeholder"](https://spectrum.corp.adobe.com/page/text-field/#Don%E2%80%99t-use-placeholder-text) due to accessibility issues. We have been advising folks to use Help text (under the field) instead of placeholder text.

So based on those reasons above, the "placeholder" text that is part of Search should be considered as a label so it has to meet contrast ratios and be the same color as a value (input).

**Comment by Westbrook** [comment] 2024-03-17 11:59
Closing as as designed.

**Closed by Westbrook** 2024-03-17 11:59 UTC
Labels: enhancement, triage
