### ISSUE TITLE
Allow close section on header click when using Allow Multiple selection true

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#1000] opened 2020-11-09 03:01 UTC
### Expected Behaviour
Able to close an open Accordion section when clicking the header (when Allow Multiple selections is enabled). 

In my case, I have a form with not a lot of available height (see side panel in software app). So I want to use an Accordion to let the user have some sections open and some closed. 

### Actual Behaviour
Unable to close Accordion section

### Reproduce Scenario (including but not limited to)
Create an accordion and set all multiple selection to true

#### Steps to Reproduce
1. Create Accordion with multiple selection to true
2. Click on a header to open it 
3. Click on an open header 

#### Platform and Version
All (or Mac OSX) 

#### Sample Code that illustrates the problem
See the example [here](https://opensource.adobe.com/spectrum-web-components/components/accordion):
https://opensource.adobe.com/spectrum-web-components/components/accordion

**Comment by Westbrook** [comment] 2020-11-09 12:53
Thanks for the issue. This is a duplicate of #920. We do have this on our roadmap, and hope to have this addition available for everyone soon.

**Closed by Westbrook** 2020-11-09 12:53 UTC
