### ISSUE TITLE
[Bug]: inner slot handled incorrectly with overlay popover

### ISSUE THREAD

**Issue by mighdoll** [adobe/spectrum-web-components#3043] opened 2023-03-18 01:23 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay, popover

### Expected behavior

inner slot content should be drawn inside the popover on click

### Actual behavior

first click: popover is empty.
second click: inner slot content is drawn w/no popover.
third click: nothing happens

### How can we reproduce this issue?

```
git clone https://github.com/mighdoll/spectrum-experiments
cd spectrum-experiments 
git checkout 0e5dab458a72f5efd3b03beae80c6297884c5024
pnpm install
pnpm vite
```

### Sample code that illustrates the problem

third slot named "inner" doesn't render correctly. 

```
    <nav-button>
      <sp-icon-bug slot="icon"></sp-icon-bug>
      bugz
      <div slot="inner">bar should display</div>
    </nav-button>
```

```
@customElement("nav-button")
export class NavButton extends LitElement {
  override render(): TemplateResult {
    return html`
      <overlay-trigger>
        <sp-action-button slot="trigger">
          <slot slot="icon" name="icon"></slot>
          <slot></slot>
        </sp-action-button>
        <sp-popover slot="click-content" dialog placement="right" open>
          where's inner?
          <slot name="inner"></slot>
        </sp-popover>
      </overlay-trigger>
    `;
  }
}
```

**Comment by Westbrook** [comment] 2023-03-30 04:01
Duplicate of #2086

**Closed by Westbrook** 2023-03-30 04:01 UTC
Labels: bug, triage
