### ISSUE TITLE
[Bug]: Tabs Overflow cuts off the focus border on tabs

### ISSUE THREAD

**Issue by hlmitchell** [adobe/spectrum-web-components#3499] opened 2023-07-28 19:56 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tabs Overflow

### Expected behavior

I expect to be able to fully see the focus border as I key through the tabs.

### Actual behavior

The focus border is cut off on the tabs. 

### Screenshots

<img width="421" alt="Screenshot 2023-07-28 at 1 39 23 PM" src="https://github.com/adobe/spectrum-web-components/assets/20149192/d3c9ed82-5fee-4cac-afd0-fe1c4cad79db">
<img width="936" alt="Screenshot 2023-07-28 at 1 38 48 PM" src="https://github.com/adobe/spectrum-web-components/assets/20149192/4d8c1644-69e4-4510-b020-22efb28cc000">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

Go to spectrum storybook. Key through the tabs to see the first tab is consistently cut off.

**Comment by Westbrook** [comment] 2023-07-28 20:34
Duplicate of #2962.

**Closed by Westbrook** 2023-07-28 20:34 UTC
Labels: bug, Component: Tabs, triage
