### ISSUE TITLE
ActionMenu support for hyperlink items

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/spectrum-web-components#820] opened 2020-08-11 17:15 UTC
### Expected Behaviour

I would like to be able to place hyperlinks in ActionMenu items.

### Actual Behaviour

Hyperlinks are (technically?) not supported in ActionMenu items.
To work around this, I have to write (small) JS that binds to the click even of each menu item, attach custom attributes for href/target, and then mimic a link click via window.open in the click handler.

**Comment by Westbrook** [comment] 2020-08-11 22:41
Thanks for bringing this up. Currently what _is_ supported is the use of the `href` attribute on the `<sp-menu-item>` directly.
```
<sp-menu-item href="https://adobe.com">
    Adobe, Inc.
</sp-menu-item>
```
Will create an `<a>` internal to the item with the appropriate attributes in tow. The extended attributes available for this style of usage are:
```
export interface LikeAnchorInterface {
    download?: string;
    label?: string;
    href?: string;
    rel?: string;
    target?: '_blank' | '_parent' | '_self' | '_top';
}
```
Do you feel there is something in specific that accepting an actual anchor element would support you doing that you don't see possible with this API clarified? If so, I'd love your extended use case so we can look to support what you're putting together!

If not, then I'll move this to a documentation issue, as we definitely need to get the grouped elements better documented.

**Comment by Westbrook** [comment] 2020-09-13 23:32
@davidjgonzalez I'm going to close this as working as intended, but please feel free to reopen/create a new issue if you have further trouble with this component.

**Closed by Westbrook** 2020-09-13 23:32 UTC
