### ISSUE TITLE
[Bug]:  Crash is happening when parent is removed from dom for selfManaged tooltip

### ISSUE THREAD

**Issue by ananpal** [adobe/spectrum-web-components#2978] opened 2023-03-02 04:04 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

* the crash should not happen
* in manageTooltip function there should be a check if the parent is already removed it should not try to remove events from parent.  

### Actual behavior

* in manageTooltip function events is being removed from parent but parent is already removed which is causing the crash.   

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment] 2023-03-07 15:51
Dupe of #2359

**Closed by Westbrook** 2023-03-07 15:51 UTC
Labels: bug, triage

**Comment by ananpal** [comment] 2023-03-27 11:30
@Westbrook this doesn't look like the duplicate of of #2359, as per the functionality wise in this bug tooltip is not getting removed rather parent is remove.

**Comment by Westbrook** [comment] 2023-03-27 12:40
We'd be happy to accept a repro that outlined the differences here, but based on our knowledge of the current and future functionality of this element we continue to see this as a duplicate.
