### ISSUE TITLE
An sp-toast element can't be re-opened

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#935] opened 2020-10-07 22:27 UTC
### Expected Behaviour
I should be able to re-use the same `sp-toast` element to display a new toast message. It also shouldn't add attributes upon initialization that are critical to it's display.

### Actual Behaviour
`sp-toast` adds an `open` attribute that gets removed once the close button is clicked. Additionally, it loses its variant attribute when closed.

This is particularly problematic when used with frameworks that re-use DOM elements. `<sp-toast>Message</sp-toast>` leads to an open toast on the first instantiation, but is closed upon re-use.

#### Steps to Reproduce

1. Close the example toast at https://opensource.adobe.com/spectrum-web-components/components/toast
2. Add an `open` tag to the closed elements in the debugger to re-open them.

**Comment by Westbrook** [comment] 2020-10-08 14:26
I see a couple of things here:
1. On construction the element current applies `this.open = true` which reflects, so it applies the attribute `open` which controls whether it is visible. This was done because it seemed like the expected response to putting an `sp-toast` element on the DOM was being able to see it, and there doesn't seem to be good cause to spend the ms of JS to boot up an element that is not visible by default. I could see requiring a user to manually apply `open` being not that big of a stretch, but I think the reality here is possibly exacerbated by the following.
2. While this element intends to dispatch a `close` event on close, it currently only does so in the timed code path. This means that manually closing the `sp-toast` element is not tracked. If it dispatched `close` more in line with all of the times that it closed, as well as an `open` event or a joined event similar to `change` or `visibility`, would you see the self management of `open` as less surprising?
3. I can't see what you're experiencing now with the loss of the `variant` attribute. If you visit https://webcomponents.dev/edit/fKR5oPuUvicCsGHMBWkT you'll see an `sp-theme` element with a `timeout`, so it will manage it self more like I think would be correct (sans the `open` relative event dispatching), and no matter how many times it is close the `variant="negative"` seems to persist. Is there a more nuanced recreation of this loss that you can share?

**Comment by adixon-adobe** [comment] 2020-10-08 17:41
1. what about changing that attribute to be `closed` instead of opened? I think the thing that's awkward here is that if I *want* the toast to be closed by default, there's no way to initialize it that way. Once it is in the DOM, I can. I'd rather have the default state of the element *reflect* that it's open, not have the element fix itself.
2. I don't think it's surprising so much as subtly problematic. If a framework is really smart about re-using DOM elements, then it's harder to know if it was just created or re-used. I could definitely see this biting us in subtle ways.
3. I was just using the web debugger to re-add the `open` attribute like this screenshot (that's from the doc page). Once added, the variant attribute gets dropped. I also saw this in the test view I'm setting up for our app when trying to bind to the `open` attribute.
<img width="318" alt="Screen Shot 2020-10-08 at 12 27 14 PM" src="https://user-images.githubusercontent.com/48841507/95494338-6375aa00-0963-11eb-8a23-b54fdccab07d.png">

**Comment by adixon-adobe** [comment] 2020-10-08 17:45
It's weird that your example is working, but this isn't. From what I can tell both are removing the `open` attribute.

**Comment by Westbrook** [comment] 2020-10-23 21:10
Thinking this through, it seems the right path here is to stop applying `open` by default, which will align this element with others in our library and with native elements like `<detail>` which manage an `open` attribute as well. From there most of the rest of the requests above _should_ just work.

To support not losing the `variant` attribute in the future (though I've still not been able to recreate this locally) we should add a unit test that take the toast on and off the DOM to ensure that our `variant` attribute is not lost there as a regression at any point in the future. 

In association with this, I believe that we should dispatch the `close` event at any point that the toast is closed, regardless of the the presence of a `timeout` value or not.

**Comment by Westbrook** [comment] 2021-01-14 03:07
Updated as discussed to be `open===false` by default.

**Closed by Westbrook** 2021-01-14 03:07 UTC
Labels: Component: Toast
