### ISSUE TITLE
[Feat][a11y]: sp-dialog: use HTMLDialogElement with show() or showModal() method

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-web-components#3374] opened 2023-06-27 20:37 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Dialog,  DialogBase, DialogWrapper, Overlay

### Description of the requested feature

Dialog component should use modern HTML5 `<dialog>` component, which automatically traps keyboard focus, handles z-index positioning, and makes underlying content `inert`.

**Comment by Westbrook** [comment] 2023-06-27 20:50
Closing as a duplicate of #2086 and the work going on in #3009

**Closed by Westbrook** 2023-06-27 20:50 UTC
Labels: enhancement, Component: Overlay, a11y, Component: Dialog, triage
