### ISSUE TITLE
[Bug]: When SpectrumSwitchElement is in focus, Keyboard presses do not work.

### ISSUE THREAD

**Issue by shreyaanand29** [adobe/spectrum-web-components#3359] opened 2023-06-26 10:42 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

SpectrumSwitchElement

### Expected behavior

The keys pressed should work properly even if the SpectrumSwitchElement is in focus.

### Actual behavior

The Keys pressed do not work if the SpectrumSwitchElement is in focus.

### How can we reproduce this issue?

1. Go to any toggle/switch element
2. Click on it to enable/disable
3. Press any key from the keyboard to perform certain operations on the application
4. Observe
5. The key pressed does not work and there is a blue outline on the toggle element in focus

**Comment by Westbrook** [comment] 2023-06-26 11:04
I'm not seeing any issue with this. See the console output in https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/uXsqJULoUuOtbDgGB4sC/src/index.ts?branch=keyboard-events%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories. Please share a reproduction of what you feel is the issue you have encountered or we'll need to close this issue as "works as expected".

**Comment by Westbrook** [comment] 2023-07-14 00:47
Without a repro, we'll need to close this issue...

**Comment by shreyaanand29** [comment] 2023-07-22 07:35
Hello, sharing a recording reproducing the bug. 
https://adobe-my.sharepoint.com/:v:/p/shreyaa/EQ-5p1yCGbdFvJO9QXER-YsBWUXL2Iorja-HF0p2LE9M9g?e=QCiD0T

**Comment by shreyaanand29** [comment] 2023-07-22 07:37
Re-iterating the steps
1. Go to any toggle/switch element
2. Click on it to enable/disable
3. Press any key from the keyboard to perform certain operations on the application(here we were trying to press cmd+z to undo and enter to open the accordian)
4. Observe thet the key pressed does not work and there is a blue outline on the toggle element in focus

**Comment by Westbrook** [comment] 2023-07-22 14:41
I've extended the demo case to include the `metaKey` and there still seems to be no issue: https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/uXsqJULoUuOtbDgGB4sC/src/index.ts?branch=keyboard-events%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories

If you're unable to provide an abstract reproduction the issue your encountering, we'll likely close this issue in the near future as "cannot reproduce". Working from the demo above, I can only assume that the issue at hand has to do with your application code, but we'd welcome a version of that link where your issue occurs so we can work together to hunt it down.

**Comment by najikahalsema** [comment] 2023-10-12 14:41
Can't reproduce

**Closed by najikahalsema** 2023-10-12 14:41 UTC
Labels: bug, Needs repro, triage
