### ISSUE TITLE
[Bug]: Tray in the Action Menu is left-aligned instead center-aligned

### ISSUE THREAD

**Issue by SavoInfostream** [adobe/spectrum-web-components#3824] opened 2023-11-23 13:13 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action Menu

### Expected behavior

When opening sp-action-menu in lower resolution the tray should be center-aligned (like the tray in picker).

### Actual behavior

Opens on the bottom left.

### Screenshots

![action menu](https://github.com/adobe/spectrum-web-components/assets/60256229/4741080b-ddd1-4b73-af78-12469c6a46e1)

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Westbrook** [comment] 2023-11-23 13:38
Duplicate of #3822

**Closed by Westbrook** 2023-11-23 13:38 UTC
Labels: bug, triage
