### ISSUE TITLE
[Bug]: <sp-picker quiet> doesn't lay out properly

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#2963] opened 2023-02-27 18:36 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

The test of `sp-picker` is vertically centered like it was previously.

### Actual behavior

It looks like there's a new [negative margin ](https://github.com/adobe/spectrum-web-components/blob/main/packages/picker/src/spectrum-picker.css#L368) on the button that probably isn't intended to be there with the quiet attribute.

The result of this is that the layout of the internal <button> element is expanding beyond the bounds of the picker, and causing the picker text to align with the top. This is noticeably off if you have a horizontal layout, which it looks the docs are lacking for picker.

It looks like we should be able to work around this by adjusting the variable used here.

### Screenshots

Here's a quick example of how things can look off:

<img width="183" alt="Screen Shot 2023-02-27 at 12 35 25 PM" src="https://user-images.githubusercontent.com/48841507/221652762-62ec1726-df45-41fa-b9c5-323271dcf5ea.png">

<img width="337" alt="Screen Shot 2023-02-27 at 12 36 01 PM" src="https://user-images.githubusercontent.com/48841507/221652873-f0c30c71-9b39-4a4b-b139-b1d62d52d6f0.png">

**Comment by adixon-adobe** [comment] 2023-02-27 18:36
I'm guessing this is also a spectrum css bug.

**Comment by blunteshwar** [comment] 2023-09-14 15:34
PR: [https://github.com/adobe/spectrum-css/pull/2169](url)

**Comment by blunteshwar** [comment] 2023-09-25 06:22
PR: https://github.com/adobe/spectrum-css/pull/2169

**Comment by jenndiaz** [comment] 2023-09-27 21:01
I do not see this is a bug. The negative margin was included in recent design guidance. 
We do have an [additional class](https://github.com/adobe/spectrum-css/blob/main/components/picker/index.css#L476) for when the label and picker are side by side, @adixon-adobe do you still see this issue when using this class? 
![Screenshot 2023-09-27 at 2 59 01 PM](https://github.com/adobe/spectrum-web-components/assets/63808889/866715ac-7cbd-47c7-a746-01cc9e2c7eed)


CC:  @pfulton @najikahalsema @blunteshwar

**Comment by blunteshwar** [comment] 2023-10-06 09:27
@jenndiaz Thanks!, after using this additional class the issue is resolved!

**Comment by blunteshwar** [comment] 2023-10-12 06:41
@jenndiaz I believe this additional class should only be applied when the label and picker are side by side but the issue is still present when the label and picker are in a top and bottom arrangement

**Comment by jenndiaz** [comment] 2023-10-12 21:37
> @jenndiaz I believe this additional class should only be applied when the label and picker are side by side but the issue is still present when the label and picker are in a top and bottom arrangement

@blunteshwar while I think using this class could still work, I think it was not clear to me when originally looking at it what was going on in the screenshot describing the bug. Chatting in slack about different options.

**Comment by jenndiaz** [comment] 2024-02-13 15:41
Fix for this is merged and released! 
- @spectrum-css/picker@7.2.3 
- @spectrum-css/fieldlabel@7.3.2

**Comment by Rajdeepc** [comment] 2024-02-21 09:38
Will take this up in SWC. Thanks @jenndiaz

**Closed** 2024-02-26 12:41 UTC
Labels: bug, Component: Picker, Spectrum CSS
