### ISSUE TITLE
[Bug]: Draggable attribute is not working with sp-swatch in Chrome webbrowser

### ISSUE THREAD

**Issue by pkashyap29** [adobe/spectrum-web-components#3746] opened 2023-10-25 08:24 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-swatch

### Expected behavior

draggable attribute should work and drag and drop functionality should work.

### Actual behavior

Unable to drag and drop sp-swatch component

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/LUsuTS9slncGL3ehLb1L/src/index.ts?p=stories

**Comment by Westbrook** [comment] 2023-10-26 12:49
This seems to work fine in Chrome. Can you give some more information about the fail state you seems to be encountering here?

**Comment by Westbrook** [comment] 2024-01-02 23:44
Closing as unable to reproduce as the demo seems draggable in Chrome.

**Closed by Westbrook** 2024-01-02 23:44 UTC
Labels: bug, triage

**Comment by pkashyap29** [comment] 2024-01-04 06:44
Hi Westbrook, Sorry I missed your earlier comment. But this Bug is specific to mobile view.
