### ISSUE TITLE
[Bug]: Spectrum slider does not give the updated value when value changed from different point than handle

### ISSUE THREAD

**Issue by anupre** [adobe/spectrum-web-components#3190] opened 2023-05-09 18:10 UTC
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

Scrubbing on slider from the slider handle or any other point should give the updated value, as well as change event occurs on pointer up. It should happen on pointer down on slider.

### Actual behavior

Scrubbing on slider from the slider handle, originates input event and it gives us the updated value and on pointer up, change event also occurs.
But if scrubbing starts from a different point than slider handle, input event doesn’t occur.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment] 2024-02-16 15:59
Closing as duplicate of #3454

**Closed by Westbrook** 2024-02-16 15:59 UTC
Labels: bug, Component: Slider
